[package]
name = "qmm-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
qmm-syntax = { path = "../qmm-syntax" }
qmm-player = { path = "../qmm-player" }
clap = { version = "4.2.4", features = ["derive"] }
tui = "0.19.0"
crossterm = "0.26.1"
